[tool.poetry]
name = "rgs"
version = "0.1.1"
description = "A simple package for displaying and manipulating random structures like pairings, Dyck paths, and tilings"
authors = ["Vladislav Kargin <slavakargin@yahoo.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.20.1"
scipy = "^1.6.1"
matplotlib = "^3.3.4"
numdifftools = "^0.9.39"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
